cabal-version:   3.0
name:            hewts
version:         0.0.0.0
synopsis:        See README for more info
description:
  See README for more info.
  See README.md for more details.

license:         BSD-3-Clause
license-file:    LICENSE
author:          Vladislav
maintainer:      Vladislav <email@email.com>
copyright:       2026 Vladislav
build-type:      Simple
extra-doc-files:
  CHANGELOG.md
  README.md

tested-with:     GHC ==9.10.3

common exec-options
  ghc-options:
    -with-rtsopts=-N1 -with-rtsopts=-qn8 -with-rtsopts=-A64m
    -with-rtsopts=-AL256m -with-rtsopts=-I0 -with-rtsopts=-T

common common-options
  build-depends:      base >=4.11 && <5
  default-language:   Haskell2010
  default-extensions:
    ConstraintKinds
    DeriveGeneric
    DerivingStrategies
    GeneralizedNewtypeDeriving
    InstanceSigs
    KindSignatures
    LambdaCase
    OverloadedStrings
    PatternSynonyms
    RecordWildCards
    ScopedTypeVariables
    StandaloneDeriving
    TupleSections
    TypeApplications
    ViewPatterns

library
  import:          common-options
  hs-source-dirs:  src
  exposed-modules:
    Convert
    Convert.Grammar.Rules.Grammar01
    Convert.Grammar.Rules.Grammar08
    Convert.Grammar.Rules.Grammar09
    Convert.Grammar.Rules.Grammar10
    Convert.Grammar.Rules.Grammar11
    Convert.Grammar.Rules.Grammar12
    Convert.Grammar.Rules.Grammar13
    Convert.Grammar.Rules.Grammar14
    Convert.Grammar.Rules.Grammar15
    Convert.Grammar.Rules.Grammar16
    Convert.Grammar.Rules.Grammar17
    Convert.Grammar.Rules.Grammar18
    Convert.Grammar.Rules.Grammar19
    Convert.Grammar.Rules.Grammar20
    Convert.Grammar.Structures
    Convert.Token
    Convert.Grammar
    Convert.Grammar.Common
    Convert.Tokenizer.Wylie
    Convert.Tokenizer.WylieLegacy
    Convert.Tokenizer.Unicode    
    Convert.Tokenizer.UnicodeLegacy    
    Syllables
    -- Convert.Grammar.Structure.Structure01
    -- Convert.Grammar.Structure.Structure02
    -- Convert.Grammar.Structure.Structure03
    -- Convert.Grammar.Structure.Structure04
    -- Convert.Grammar.Structure.Structure05
    -- Convert.Grammar.Structure.Structure06
    -- Convert.Grammar.Structure.Structure07
    -- Convert.Grammar.Structure.Structure08
    -- Convert.Grammar.Structure.Structure09
    -- Convert.Grammar.Structure.Structure10
    -- Convert.Grammar.Structure.Structure11
    -- Convert.Grammar.Structure.Structure12
    -- Convert.Grammar.Structure.Structure13
    -- Convert.Grammar.Structure.Structure14
    -- Convert.Grammar.Structure.Structure15
    -- Convert.Grammar.Structure.Structure16
    -- Convert.Grammar.Structure.Structure17
    -- Convert.Grammar.Structure.Structure18
    -- Convert.Grammar.Structure.Structure19
    -- Convert.Grammar.Structure.Structure20

  build-depends:
    , bytestring
    , extra
    , massiv
    , megaparsec
    , pretty-simple
    , text
    , unordered-containers
    , bytestring-trie

executable hewts
  import:         common-options
  hs-source-dirs: app
  main-is:        Main.hs
  build-depends:  hewts
  ghc-options:    -threaded -rtsopts -with-rtsopts=-N

test-suite hewts-test
  import:         common-options
  type:           exitcode-stdio-1.0
  hs-source-dirs: test
  main-is:        Spec.hs
  other-modules:
    Test.Tokenizer.Types
    Test.Tokenizer.Spans
    Test.Tokenizer.Tricky
    Test.Tokenizer.Integration
    Test.Tokenizer.Golden

  build-depends:
    hewts,
    bytestring,
    text,
    tasty,
    tasty-hunit,
    tasty-golden
  ghc-options:    -threaded -rtsopts -with-rtsopts=-N

benchmark hewts-benchmark
  import:         common-options
  type:           exitcode-stdio-1.0
  hs-source-dirs: benchmark
  main-is:        Main.hs

  -- build-depends:  hewts
  ghc-options:    -threaded -rtsopts -with-rtsopts=-N
