cabal-version:   3.0
name:            hewts
version:         0.0.0.0
synopsis:        See README for more info
description:
  See README for more info.
  See README.md for more details.

license:         BSD-3-Clause
license-file:    LICENSE
author:          Vladislav
maintainer:      Vladislav <email@email.com>
copyright:       2026 Vladislav
build-type:      Simple
extra-doc-files:
  CHANGELOG.md
  README.md

tested-with:     GHC ==9.6.7

common exec-options
  ghc-options:
    -with-rtsopts=-N1 -with-rtsopts=-qn8 -with-rtsopts=-A64m
    -with-rtsopts=-AL256m -with-rtsopts=-I0 -with-rtsopts=-T

common common-options
  build-depends:      base >=4.11 && <5
  default-language:   Haskell2010
  default-extensions:
    ConstraintKinds
    DeriveGeneric
    DerivingStrategies
    GeneralizedNewtypeDeriving
    InstanceSigs
    KindSignatures
    LambdaCase
    OverloadedStrings
    PatternSynonyms
    RecordWildCards
    ScopedTypeVariables
    StandaloneDeriving
    TupleSections
    TypeApplications
    ViewPatterns

library
  import:          common-options
  hs-source-dirs:  src
  exposed-modules:
    Convert
    Convert.WylieUnicode
    Parser
    Parser.Common
    Parser.Structure
    Parser.Structure.Structure1
    Parser.Structure.Structure2
    Parser.Structure.Structure3
    Parser.Structure.Structure4
    Parser.Structure.Structure5
    Parser.Structure.Structure6
    Parser.Structure.Structure7
    Syllables

  build-depends:
    , bytestring
    , extra
    , massiv
    , megaparsec
    , pretty-simple
    , text
    , unordered-containers

executable hewts
  import:         common-options
  hs-source-dirs: app
  main-is:        Main.hs
  build-depends:  hewts
  ghc-options:    -threaded -rtsopts -with-rtsopts=-N

test-suite hewts-test
  import:         common-options
  type:           exitcode-stdio-1.0
  hs-source-dirs: test
  main-is:        Spec.hs

  -- build-depends:  hewts
  ghc-options:    -threaded -rtsopts -with-rtsopts=-N

benchmark hewts-benchmark
  import:         common-options
  type:           exitcode-stdio-1.0
  hs-source-dirs: benchmark
  main-is:        Main.hs

  -- build-depends:  hewts
  ghc-options:    -threaded -rtsopts -with-rtsopts=-N
