cabal-version: 3.0
name: hewts
version: 0.0.0.0
synopsis: See README for more info
description:
  See README for more info.
  See README.md for more details.

license: BSD-3-Clause
license-file: LICENSE
author: Vladislav
maintainer: Vladislav <email@email.com>
copyright: 2026 Vladislav
build-type: Simple
extra-doc-files:
  CHANGELOG.md
  README.md
  test/vectors/*.tsv
  test/vectors/kang.txt
  test/vectors/README.md

tested-with: ghc ==9.10.3

common exec-options
  ghc-options:
    -with-rtsopts=-N1
    -with-rtsopts=-qn8
    -with-rtsopts=-A64m
    -with-rtsopts=-AL256m
    -with-rtsopts=-I0
    -with-rtsopts=-T

common common-options
  build-depends: base >=4.11 && <5
  default-language: Haskell2010
  default-extensions:
    ConstraintKinds
    DeriveGeneric
    DerivingStrategies
    GeneralizedNewtypeDeriving
    InstanceSigs
    KindSignatures
    LambdaCase
    OverloadedStrings
    PatternSynonyms
    RecordWildCards
    ScopedTypeVariables
    StandaloneDeriving
    TupleSections
    TypeApplications
    ViewPatterns

library
  import: common-options
  hs-source-dirs: src
  exposed-modules:
    Convert
    Convert.Diagnostic
    Convert.Grammar.Constraint
    Convert.Grammar.Parser
    Convert.Grammar.Structure
    Convert.Grammar.Syllable
    Convert.Sentence
    Convert.Token
    Convert.Tokenizer.Unicode
    Convert.Tokenizer.Wylie

  other-modules:
    Convert.Grammar.Constraint.Constraint01
    Convert.Grammar.Constraint.Constraint08
    Convert.Grammar.Constraint.Constraint09
    Convert.Grammar.Constraint.Constraint10
    Convert.Grammar.Constraint.Constraint11
    Convert.Grammar.Constraint.Constraint12
    Convert.Grammar.Constraint.Constraint13
    Convert.Grammar.Constraint.Constraint14
    Convert.Grammar.Constraint.Constraint15
    Convert.Grammar.Constraint.Constraint16
    Convert.Grammar.Constraint.Constraint17
    Convert.Grammar.Constraint.Constraint18
    Convert.Grammar.Constraint.Constraint19
    Convert.Grammar.Constraint.Constraint20
    Convert.Grammar.Constraint.Constraint21

  build-depends:
    bytestring,
    bytestring-trie,
    containers,
    extra,
    massiv,
    megaparsec,
    pretty-simple,
    text,
    transformers,
    unordered-containers,

test-suite hewts-test
  import: common-options
  type: exitcode-stdio-1.0
  hs-source-dirs: test
  main-is: Spec.hs
  other-modules:
    Test.Convert
    Test.Convert.Golden
    Test.Convert.Sentence
    Test.Diagnostic
    Test.Grammar.Constraint.Constraint01
    Test.Grammar.Constraint.Constraint08
    Test.Grammar.Constraint.Constraint09
    Test.Grammar.Constraint.Constraint10
    Test.Grammar.Constraint.Constraint11
    Test.Grammar.Constraint.Constraint12
    Test.Grammar.Constraint.Constraint13
    Test.Grammar.Constraint.Constraint14
    Test.Grammar.Constraint.Constraint15
    Test.Grammar.Constraint.Constraint16
    Test.Grammar.Constraint.Constraint17
    Test.Grammar.Constraint.Constraint18
    Test.Grammar.Constraint.Constraint19
    Test.Grammar.Constraint.Constraint20
    Test.Grammar.Stack
    Test.Grammar.Structure
    Test.Grammar.Wylie
    Test.Parity
    Test.Tokenizer.Golden
    Test.Tokenizer.Integration
    Test.Tokenizer.RoundTrip
    Test.Tokenizer.Spans
    Test.Tokenizer.Tricky
    Test.Tokenizer.Types

  build-depends:
    bytestring,
    containers,
    hewts,
    tasty,
    tasty-golden,
    tasty-hunit,
    text,
    unordered-containers,

  ghc-options:
    -threaded
    -rtsopts
    -with-rtsopts=-N

benchmark hewts-benchmark
  import: common-options
  type: exitcode-stdio-1.0
  hs-source-dirs: benchmark
  main-is: Main.hs
  -- build-depends:  hewts
  ghc-options:
    -threaded
    -rtsopts
    -with-rtsopts=-N
