sudo: true
dist: bionic

language: generic

cache:
  directories:
    - $HOME/.stack
    - .stack-work
  timeout: 1000

jobs:
  include:
    - stage: "Build the backend"
      before_script:
        - sudo apt-get install -y libgmp-dev
        - curl -sSL https://get.haskellstack.org/ | sh
        # travis_retry works around https://github.com/commercialhaskell/stack/issues/4888
        - travis_retry stack setup
      script:
        # Build
        - stack --no-terminal build --test --no-run-tests --dependencies-only
        - stack --no-terminal build --test --no-run-tests
      before_cache:
        - rm -rf $HOME/.stack/programs  # GHC is faster to install than to cache
    - stage: "Hlint"
      before_script:
        - sudo apt-get install -y libgmp-dev
        - curl -sSL https://get.haskellstack.org/ | sh
        # travis_retry works around https://github.com/commercialhaskell/stack/issues/4888
        - travis_retry stack setup
        - stack install hlint
      script:
        # Check
        - hlint .
      before_cache:
        - rm -rf $HOME/.stack/programs  # GHC is faster to install than to cache
