sudo: true
dist: bionic

language: generic

# git:
#   depth: 5

cache:
  directories:
  - "$HOME/.stack"
  - .stack-work
  # timeout: 1000



# matrix:
#   include:
#   - env: GHC='8.10.7'
#     os: linux
#   - env: GHC='8.10.7'
#     os: osx

jobs:
  include:
    - stage: "Build the backend"
      before_install:
        - sudo apt-get install -y libgmp-dev

        # HLint check
        - curl -sSL https://raw.github.com/ndmitchell/neil/master/misc/travis.sh | sh -s -- hlint .

      install:
        # install stack and build project
        - curl -sSL https://get.haskellstack.org/ | sh
        - travis_retry stack setup
        - stack --version
        # build project
        - stack build --test --no-run-tests --no-terminal --dependencies-only

      script:
        # test project
        - stack build --no-terminal --test

      # before_cache:
        # - rm -rf $HOME/.stack/programs  # GHC is faster to install than to cache

notifications:
  email: false
