resolver: lts-20.1

packages:
- .

extra-deps:
- polysemy-1.7.1.0
- polysemy-plugin-0.4.3.1
- polysemy-conc-0.9.0.0
- polysemy-resume-0.5.0.0
- polysemy-time-0.5.1.0
- incipit-base-0.3.0.0
- incipit-core-0.3.0.0

- radixtree-0.6.0.0

- tomland-1.3.3.2
- validation-selective-0.1.0.2

ghc-options:
  "$locals": -fhide-source-paths

# build:
#   library-profiling: true
#   executable-profiling: true
