resolver: lts-13.19

extra-deps:
    - path-io-1.4.0
    - radixtree-0.4.0.0
    - tomland-1.1.0.1
    - megaparsec-7.0.5
    - parser-combinators-1.2.0
    - parsers-megaparsec-0.1.0.1

ghc-options:
  "$locals": -fhide-source-paths

