resolver: lts-21.25

packages:
- .

extra-deps:
- radixtree-0.6.0.0

- tomland-1.3.3.2
- validation-selective-0.2.0.0
- log-effectful-1.0.0.0
- resourcet-effectful-1.0.1.0

ghc-options:
  "$locals": -fhide-source-paths

system-ghc: true
notify-if-nix-on-path: false

# build:
#   library-profiling: true
#   executable-profiling: true
