resolver: lts-20.26

packages:
- .

extra-deps:
- radixtree-0.6.0.0

- tomland-1.3.3.2
- validation-selective-0.1.0.2
- log-effectful-1.0.0.0
- log-base-0.12.0.0
- resourcet-effectful-1.0.0.0

ghc-options:
  "$locals": -fhide-source-paths

system-ghc: true

# build:
#   library-profiling: true
#   executable-profiling: true
