# resolver: nightly-2020-11.-04
resolver: lts-18.13

packages:
- .

extra-deps:
- parsers-megaparsec-0.1.0.1@sha256:eda0fa6cb3e2efeeea31ba373e7ee6cc5cb24efa485d082818e9084c4d804799,1724
- megaparsec-8.0.0@sha256:362f85e243ecbcb550e1de6e5c74ba5a50c09edaa1208c99bc5b9fd242227fc6,3808
- git: https://gitlab.com/transportengineering/radixtree
  commit: 94462dfdca5d01ea445642ced7aad136deab2c1a

ghc-options:
  "$locals": -fhide-source-paths

# build:
#   library-profiling: true
#   executable-profiling: true
