resolver: lts-19.11

packages:
- .

extra-deps:
- polysemy-1.7.1.0
- polysemy-plugin-0.4.3.0

- git: https://gitlab.homotopic.tech/metaxis/polysemy-extra
  commit: b3f53c7fd7385e2d2e6bcca07e92a1f2f28f8704

- git: https://gitlab.homotopic.tech/metaxis/polysemy-kvstore
  commit: 5e5e247fffc77aa67f03825dbfcc51f0dec2fb30

- git: https://gitlab.homotopic.tech/metaxis/polysemy-path
  commit: 3bfdc69b9a96055b07427f29f6b246ef0a71cea8

- radixtree-0.6.0.0
- tomland-1.3.3.1
- validation-selective-0.1.0.1
- selective-0.4.2

ghc-options:
  "$locals": -fhide-source-paths

# build:
#   library-profiling: true
#   executable-profiling: true

setup-info:
  ghc:
    linux64-tinfo6:
      9.0.2:
        url: "https://downloads.haskell.org/ghc/9.0.2/ghc-9.0.2a-x86_64-fedora27-linux.tar.xz"
