resolver: lts-20.26

packages:
- .

extra-deps:
- polysemy-1.9.0.0
- polysemy-conc-0.12.1.0
- polysemy-resume-0.7.0.0
- polysemy-time-0.6.0.0
- incipit-base-0.5.1.0
- incipit-core-0.5.1.0

- radixtree-0.6.0.0

- tomland-1.3.3.2
- validation-selective-0.1.0.2

ghc-options:
  "$locals": -fhide-source-paths

system-ghc: true

# build:
#   library-profiling: true
#   executable-profiling: true
