name: Build bot

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: GHC ${{ matrix.ghc-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ghc-version: ['9.6.7']

    steps:
      - uses: actions/checkout@v4

      - name: Set up GHC
        uses: haskell-actions/setup@v2
        id: setup
        with:
          ghc-version: ${{ matrix.ghc-version }}
          cabal-version: '3.16.0.0'
          cabal-update: true

      - name: Configure the build
        run: |
          cabal configure --enable-tests --enable-benchmarks --disable-documentation
          cabal build all --dry-run

      - name: restore cache
        uses: actions/cache/restore@v4
        with:
          key: ${{ runner.os }}-${{ matrix.ghc-version }}-${{ github.sha }}
          path: ~/.cabal/store
          restore-keys: ${{ runner.os }}-${{ matrix.ghc-version }}-

      - name: Install dependencies
        # If we had an exact cache hit, the dependencies will be up to date.
        if: steps.cache.outputs.cache-hit != 'true'
        run: cabal build all --only-dependencies

      - name: save cache
        if: always()
        uses: actions/cache/save@v4
        with:
          key: ${{ runner.os }}-${{ matrix.ghc-version }}-${{ github.sha }}
          path: ~/.cabal/store

      - name: Build dependencies
        run: cabal build --only-dependencies --enable-tests --enable-benchmarks

      - name: Build project
        run: cabal build --enable-tests --enable-benchmarks

      - name: Run tests
        run: cabal test

      - name: Cabal check
        run: cabal check
      
      - name: Haddock
        run: cabal haddock --haddock-all --disable-documentation
